# Generated by Django 3.1 on 2021-09-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pdf_file',
            field=models.CharField(default='No_Location', max_length=500),
        ),
        migrations.AddField(
            model_name='image',
            name='tagged',
            field=models.BooleanField(default=False),
        ),
    ]
