# Generated by Django 3.1 on 2021-10-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20211001_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video_file',
            field=models.CharField(default='No Location', max_length=500),
        ),
    ]
