# Generated by Django 3.1 on 2021-10-02 12:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_image_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tags',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='image',
            name='data',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
